### ISSUE TITLE
Error for camera permission 

### ISSUE THREAD

**Issue by Aditya-jain23** [Aditya-jain23/SwiftShop-MobileApplication#1]
Try looking into androidmanifest.xml file

**Comment by PrabhSethi** [comment]
You did not give permission to camera or haptics. It is been resolved by adding 2 lines of code in androidmanifest.xml, the lines are. 
<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.VIBRATE"/>

**Comment by PrabhSethi** [comment]
You did not give permission to camera or haptics. It is been resolved by adding 2 lines of code in androidmanifest.xml, the lines are<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.VIBRATE"/>
